# Generated by Django 5.0.6 on 2024-06-14 07:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('technology', 'Technology'), ('culture', 'Culture'), ('sports', 'Sports'), ('business', 'Business'), ('travel', 'Travel'), ('economy', 'Economy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
