# Generated by Django 5.1.6 on 2025-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Technology', 'Technology'), ('Culture', 'Culture'), ('Sports', 'Sports'), ('Business', 'Business'), ('Travel', 'Travel'), ('Economy', 'Economy')], max_length=20),
        ),
    ]
