# Generated by Django 5.0.6 on 2024-05-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
    ]
